# Generated by Django 2.0.2 on 2018-02-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Send',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=25)),
                ('receiver', models.CharField(max_length=25)),
                ('text', models.TextField()),
            ],
        ),
    ]
